---
# Source: CUE apiObjects.Deployment.httpbin
metadata:
  name: httpbin
  namespace: holos-system
  labels:
    app: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
      app.kubernetes.io/instance: httpbin
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        app: httpbin
        app.kubernetes.io/instance: httpbin
    spec:
      containers:
        - name: httpbin
          image: quay.io/holos/mccutchen/go-httpbin
          ports:
            - containerPort: 8080
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 8192
            runAsGroup: 8192
            capabilities:
              drop:
                - ALL
      securityContext:
        seccompProfile:
          type: RuntimeDefault
kind: Deployment
apiVersion: apps/v1
---
# Source: CUE apiObjects.ReferenceGrant.istio-gateways
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: httpbin
  namespace: holos-system
  labels:
    app: httpbin
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: istio-gateways
  to:
    - group: ""
      kind: Service
---
# Source: CUE apiObjects.Service.httpbin
metadata:
  name: httpbin
  namespace: holos-system
  labels:
    app: httpbin
spec:
  selector:
    app: httpbin
    app.kubernetes.io/instance: httpbin
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
kind: Service
apiVersion: v1
