apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-crds
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./deploy/clusters/workload/components/postgres-crds
    repoURL: git@github.com:holos-run/holos-k3d.git
    targetRevision: HEAD
