---
# Source: CUE apiObjects.HTTPRoute.httpbin
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: istio-gateways
  labels:
    app: httpbin
spec:
  hostnames:
    - httpbin.holos.localhost
  parentRefs:
    - name: default
      namespace: istio-gateways
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: httpbin
          namespace: holos-system
          port: 80
