---
# Source: CUE apiObjects.HTTPRoute.authproxy
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authproxy
  namespace: istio-gateways
  labels:
    app.kubernetes.io/name: authproxy
spec:
  parentRefs:
    - name: default
      namespace: istio-gateways
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /holos/authproxy
      backendRefs:
        - name: authproxy
          namespace: istio-gateways
          port: 4180
    - matches:
        - path:
            type: PathPrefix
            value: /holos/httpbin/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: httpbin
          namespace: holos-system
          port: 80
