---
# Source: CUE apiObjects.HTTPRoute.argocd
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
spec:
  hostnames:
    - argocd.holos.localhost
  parentRefs:
    - name: default
      namespace: istio-gateways
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          port: 80
          namespace: argocd
metadata:
  name: argocd
  namespace: istio-gateways
