---
# Source: CUE apiObjects.ConfigMap.authproxy
metadata:
  name: authproxy
  namespace: istio-gateways
  labels:
    app.kubernetes.io/name: authproxy
    app.kubernetes.io/part-of: default-gateway
data:
  config.yaml: |
    injectResponseHeaders:
      - name: x-oidc-id-token
        values:
          - claim: id_token
      - name: x-auth-request-email
        values:
          - claim: email
      - name: x-auth-request-groups
        values:
          - claim: groups
      - name: x-forwarded-email
        values:
          - claim: email
      - name: x-forwarded-user
        values:
          - claim: email
      - name: x-forwarded-preferred-username
        values:
          - claim: preferred_username
    providers:
      - id: Holos Platform
        name: Holos Platform
        provider: oidc
        scope: openid profile email groups offline_access
        clientID: 275804490387516853@holos_quickstart
        clientSecretFile: /dev/null
        code_challenge_method: S256
        loginURLParameters:
          - default:
              - force
            name: approval_prompt
        oidcConfig:
          issuerURL: https://login.holos.run
          audienceClaims:
            - aud
          emailClaim: email
          groupsClaim: groups
          userIDClaim: email
    server:
      BindAddress: :4180
    upstreamConfig:
      upstreams:
        - id: static://200
          path: /
          static: true
          staticCode: 200
kind: ConfigMap
apiVersion: v1
---
# Source: CUE apiObjects.ConfigMap.authproxy-redis
metadata:
  name: authproxy-redis
  namespace: istio-gateways
  labels:
    app.kubernetes.io/name: authproxy-redis
    app.kubernetes.io/part-of: default-gateway
data:
  redis.conf: |-
    maxmemory 128mb
    maxmemory-policy allkeys-lru
kind: ConfigMap
apiVersion: v1
---
# Source: CUE apiObjects.Deployment.authproxy
metadata:
  name: authproxy
  namespace: istio-gateways
  labels:
    app.kubernetes.io/name: authproxy
    app.kubernetes.io/part-of: default-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authproxy
      app.kubernetes.io/part-of: default-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authproxy
        app.kubernetes.io/part-of: default-gateway
        sidecar.istio.io/inject: "true"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: quay.io/holos/oauth2-proxy:v7.6.0-1-g77a03ae2
          imagePullPolicy: IfNotPresent
          name: oauth2-proxy
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          args:
            - --proxy-prefix=/holos/authproxy
            - --email-domain=*
            - --session-store-type=redis
            - --redis-connection-url=redis://authproxy-redis:6379
            - --cookie-refresh=12h
            - --cookie-expire=2160h
            - --cookie-secure=true
            - --cookie-name=__Secure-workload-authproxy
            - --cookie-samesite=lax
            - --cookie-domain=.workload.holos.localhost
            - --cookie-domain=workload.holos.localhost
            - --cookie-domain=.holos.localhost
            - --cookie-domain=holos.localhost
            - --whitelist-domain=.workload.holos.localhost
            - --whitelist-domain=workload.holos.localhost
            - --whitelist-domain=.holos.localhost
            - --whitelist-domain=holos.localhost
            - --cookie-csrf-per-request=true
            - --cookie-csrf-expire=120s
            - --skip-auth-preflight=true
            - --real-client-ip-header=X-Forwarded-For
            - --skip-provider-button=true
            - --auth-logging
            - --alpha-config=/config/config.yaml
          env:
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  key: cookiesecret
                  name: authproxy
          ports:
            - containerPort: 4180
              protocol: TCP
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 8192
            runAsGroup: 8192
            capabilities:
              drop:
                - ALL
      volumes:
        - name: config
          configMap:
            name: authproxy
kind: Deployment
apiVersion: apps/v1
---
# Source: CUE apiObjects.Deployment.authproxy-redis
metadata:
  name: authproxy-redis
  namespace: istio-gateways
  labels:
    app.kubernetes.io/name: authproxy-redis
    app.kubernetes.io/part-of: default-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authproxy-redis
      app.kubernetes.io/part-of: default-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authproxy-redis
        app.kubernetes.io/part-of: default-gateway
        sidecar.istio.io/inject: "true"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - command:
            - redis-server
            - /redis-master/redis.conf
          env:
            - name: MASTER
              value: "true"
          image: quay.io/holos/redis:7.2.4
          livenessProbe:
            initialDelaySeconds: 15
            tcpSocket:
              port: redis
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: "0.5"
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: config
      volumes:
        - emptyDir: {}
          name: data
        - configMap:
            name: authproxy-redis
          name: config
kind: Deployment
apiVersion: apps/v1
---
# Source: CUE apiObjects.Service.authproxy
metadata:
  name: authproxy
  namespace: istio-gateways
  labels:
    app.kubernetes.io/name: authproxy
    app.kubernetes.io/part-of: default-gateway
spec:
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: authproxy
    app.kubernetes.io/part-of: default-gateway
kind: Service
apiVersion: v1
---
# Source: CUE apiObjects.Service.authproxy-redis
metadata:
  name: authproxy-redis
  namespace: istio-gateways
  labels:
    app.kubernetes.io/name: authproxy-redis
    app.kubernetes.io/part-of: default-gateway
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app.kubernetes.io/name: authproxy-redis
    app.kubernetes.io/part-of: default-gateway
  type: ClusterIP
kind: Service
apiVersion: v1
